---
# Copyright 2018, SUSE LINUX GmbH.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Full context: this file should be used with the openstack-helm-infra
# repository, where nodesets and jobs are defined.
- project:
    templates:
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - openstack-helm-lint
        - openstack-helm-bandit
        # Yoga
        - openstack-helm-cinder-yoga-ubuntu_focal
        - openstack-helm-compute-kit-yoga-ubuntu_focal
        # Zed
        - openstack-helm-cinder-zed-ubuntu_focal
        - openstack-helm-cinder-zed-ubuntu_jammy
        - openstack-helm-compute-kit-zed-ubuntu_focal
        - openstack-helm-compute-kit-zed-ubuntu_jammy
        # 2023.1
        - openstack-helm-cinder-2023-1-ubuntu_focal  # 3 nodes
        - openstack-helm-cinder-2023-1-ubuntu_jammy  # 3 nodes rook
        - openstack-helm-compute-kit-2023-1-ubuntu_focal  # 3 nodes
        - openstack-helm-compute-kit-2023-1-ubuntu_jammy  # 3 nodes
        # 2023.2
        - openstack-helm-horizon-2023-2-ubuntu_jammy  # 1 node
        - openstack-helm-keystone-ldap-2023-2-ubuntu_jammy  # 1 node
        - openstack-helm-cinder-2023-2-ubuntu_jammy  # 3 nodes rook
        - openstack-helm-compute-kit-2023-2-ubuntu_jammy  # 3 nodes
        - openstack-helm-tls-2023-2-ubuntu_jammy  # 1 node 32GB
        - openstack-helm-umbrella-2023-2-ubuntu_jammy  # 1 node 32GB
    gate:
      jobs:
        - openstack-helm-lint
        - openstack-helm-cinder-2023-1-ubuntu_focal
        - openstack-helm-compute-kit-2023-1-ubuntu_focal
    post:
      jobs:
        - publish-openstack-helm-charts
    experimental:
      jobs:
        - openstack-helm-apparmor-compute-kit-2023-1-ubuntu_focal
        - openstack-helm-apparmor-cinder-2023-1-ubuntu_focal
        - openstack-helm-netpol-compute-kit-2023-1-ubuntu_focal
        - openstack-helm-netpol-cinder-2023-1-ubuntu_focal
        - openstack-helm-tls-2023-1-ubuntu_focal
        - openstack-helm-tungsten-fabric-2023-1-ubuntu_focal
        - openstack-helm-tacker-2023-1-ubuntu_focal
    periodic-weekly:
      jobs:
        # Zed
        - openstack-helm-horizon-zed-ubuntu_focal
        - openstack-helm-horizon-zed-ubuntu_jammy
        - openstack-helm-umbrella-zed-ubuntu_focal
        - openstack-helm-umbrella-zed-ubuntu_jammy
